-- dish listings table
create table public.dish_listings (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null default '"::text'::text,
  description text null default '"::text'::text,
  image_url text null,
  location character varying null,
  host character varying null,
  price real null,
  host_id uuid not null default gen_random_uuid (),
  available_dates jsonb null,
  price_category text null,
  ingredients jsonb null,
  cuisine text not null default 'Other'::text,
  constraint dish_listings_pkey primary key (id),
  constraint dish_listings_host_id_fkey foreign KEY (host_id) references hosts (id)
) TABLESPACE pg_default;

-- hosts table
create table public.hosts (
  id uuid not null default gen_random_uuid (),
  name text not null,
  profile_picture_url text null,
  bio text null,
  is_verified boolean not null default false,
  constraint hosts_pkey primary key (id)
) TABLESPACE pg_default;

-- reviews table
create table public.reviews (
  id serial not null,
  dish_id integer null,
  reviewer_name text not null,
  comment text not null,
  rating numeric(3, 2) null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  review_image text null,
  review_date timestamp with time zone null default now(),
  constraint reviews_pkey primary key (id),
  constraint reviews_dish_id_fkey foreign KEY (dish_id) references dish_listings (id) on delete CASCADE,
  constraint reviews_rating_check check (
    (
      (rating >= (0)::numeric)
      and (rating <= (5)::numeric)
    )
  )
) TABLESPACE pg_default;

-- bookings table
create table public.bookings (
  id bigserial not null,
  dish_id integer not null,
  booking_date timestamp with time zone null default now(),
  selected_date date not null,
  guest_count integer not null,
  total_price real not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  is_verified_host boolean null,
  price_category text null,
  constraint bookings_pkey primary key (id),
  constraint bookings_dish_id_fkey foreign KEY (dish_id) references dish_listings (id) on delete CASCADE,
  constraint bookings_guest_count_check check ((guest_count > 0)),
  constraint bookings_total_price_check check ((total_price >= (0)::double precision))
) TABLESPACE pg_default;